### ISSUE TITLE
nodeos for EOS Mainnet not will use 100% CPU when replaying blocks to mindreader

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#107] opened 2020-07-30 19:58 UTC
When using mindreader-stdin connected to nodeos with local full copy of blocks.log in replay mode (no p2p connections) on SSD, nodeos will not use 100% CPU. (If not conntected to Mindreader it will use 100% CPU)  

I am guessing there is something within mindreader that is not processing data fast enough for the very big blocks that are on EOS Mainnet right now.

![image](https://user-images.githubusercontent.com/26171839/88968469-61b1ab00-d27d-11ea-86c5-5eb3b6f69872.png)

**Comment by sduchesneau** [comment] 2020-07-30 20:43
I can reproduce locally, I will investigate

**Comment by matthewdarwin** [comment] 2020-07-30 21:58
Also reproduced on WAX with the same setup (local blocks.log, no p2p connections).  Starting from block 1.

**Comment by sduchesneau** [comment] 2020-07-31 13:43
got some numbers for a chain with almost no blocks at all:

1) without "merge-and-store-directly", I'm getting nodeos using somewhere between 10~20% cpu
2) with "merge-and-store-directly", I'm getting nodeos using 20% cpu consistently
3) if I also disable the "abicodec" functions in code (don't do this at home, kids!), the cpu is going up to 80% for nodeos
4) if I also disable memory/cpu profiling on the go process completely (with runtime.MemProfileRate, etc.) it goes up to 94%  (however, it does not affect performance if abicodec is still doing its job)

I am investigating how to optimize the abicodec step (we DO need it to produce the block files!), and I'll add a flag to make profiling optional

**Comment by sduchesneau** [comment] 2020-07-31 19:01
I got some small improvements in there (I see a bump from 20% to 25% cpu usage on my laptop), but the remaining issue is that the ABI decoding step is parallel at the action level (to speed up decoding tons of them per block, like EOS mainnet...). 

However, since it treats one block at a time, it stops being efficient for really small (empty...) blocks. It still needs to process the eosio::onblock action on every block, but it does so at a certain cost (memory and stack allocations, etc.).

Hypothesis for further optimizations:
 1) debounce the ABI decoding by parallelizing at the block level (block 5 ABI can be fully dedocded as soon as we know that block 4 does not contain action:setABI on its actions..
 2) do not use the general-usage dhammer library, but reduce threads, interfaces and objects generated by optimizing this specific task, which can be run in parallel bot not batched)
 3) frequent actions like onblock could be written in Go -- requires validation that this chain's actual ABI is compatible before using that optimized code -- instead of the general-use eos-go ABI decoder..

Note that I cannot reproduce the perf hit of the profiling at the moment.

**Comment by sduchesneau** [comment] 2020-08-11 19:11
last commit f9eb3e6e387567dc6832bcb6f4efaae1e1c35946 addresses the issue considerably

**Comment by matthewdarwin** [comment] 2020-08-11 19:45
Ok, much better.  I consider this issue resolved enough to not be a blocker.

**Comment by sduchesneau** [comment] 2020-08-11 19:51
closing issue. further improvements are possible, but current perf is not 'obviously' an issue anymore.

**Closed by sduchesneau** 2020-08-11 19:51 UTC
